### ISSUE TITLE
Handling for password on creation/update

### ISSUE THREAD

**Issue by michag86** [univention/ansible-modules#17]
I would like to create a user with a task that looks like this:
```
  tasks:
  - name: create a user
    univention.ucs_modules.univention_directory_manager:
      module: 'users/user'
      state: 'present'
      position: 'ou=orgunit,dc=mydomain,dc=net'
      set_properties:
        - property: 'username'
          value: 'testuser1'
        - property: 'lastname'
          value: 'testuser1'
        - property: 'password'
          value: 'super_secret_password'
```
When I run the playbook a second time, it results in this message:
```
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/univention/udm/modules/generic.py", line 201, in save
    self.dn = self._orig_udm_object.modify()
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/users/user.py", line 1304, in modify
    return super(object, self).modify(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 650, in modify
    dn = self._modify(modify_childs, ignore_license=ignore_license, response=response, serverctrls=serverctrls)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 1358, in _modify
    ml = self._ldap_modlist()
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/users/user.py", line 1572, in _ldap_modlist
    ml = self._check_password_history(ml, pwhistoryPolicy)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/users/user.py", line 1646, in _check_password_history
    raise univention.admin.uexceptions.pwalreadyused()
univention.admin.uexceptions.pwalreadyused: Das Passwort wurde bereits verwendet. Bitte wählen Sie ein anderes.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 107, in <module>
  File "<stdin>", line 99, in _ansiballz_main
  File "<stdin>", line 48, in invoke_module
  File "/usr/lib/python3.7/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_univention.ucs_modules.univention_directory_manager_payload_44udolus/ansible_univention.ucs_modules.univention_directory_manager_payload.zip/ansible_collections/univention/ucs_modules/plugins/modules/univention_directory_manager.py", line 369, in <module>
  File "/tmp/ansible_univention.ucs_modules.univention_directory_manager_payload_44udolus/ansible_univention.ucs_modules.univention_directory_manager_payload.zip/ansible_collections/univention/ucs_modules/plugins/modules/univention_directory_manager.py", line 355, in run_module
  File "/tmp/ansible_univention.ucs_modules.univention_directory_manager_payload_44udolus/ansible_univention.ucs_modules.univention_directory_manager_payload.zip/ansible_collections/univention/ucs_modules/plugins/modules/univention_directory_manager.py", line 217, in _modify_object
  File "/usr/lib/python3/dist-packages/univention/udm/modules/generic.py", line 207, in save
    ), sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/univention/udm/modules/generic.py", line 201, in save
    self.dn = self._orig_udm_object.modify()
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/users/user.py", line 1304, in modify
    return super(object, self).modify(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 650, in modify
    dn = self._modify(modify_childs, ignore_license=ignore_license, response=response, serverctrls=serverctrls)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 1358, in _modify
    ml = self._ldap_modlist()
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/users/user.py", line 1572, in _ldap_modlist
    ml = self._check_password_history(ml, pwhistoryPolicy)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/users/user.py", line 1646, in _check_password_history
    raise univention.admin.uexceptions.pwalreadyused()
univention.udm.exceptions.ModifyError: Error saving 'users/user' object at 'uid=testuser1,ou=orgunit,dc=mydomain,dc=net': Das Passwort wurde bereits verwendet. Bitte wählen Sie ein anderes.
fatal: [thotuvt1]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/usr/lib/python3/dist-packages/univention/udm/modules/generic.py\", line 201, in save\n    self.dn = self._orig_udm_object.modify()\n  File \"/usr/lib/python3/dist-packages/univention/admin/handlers/users/user.py\", line 1304, in modify\n    return super(object, self).modify(*args, **kwargs)\n  File \"/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py\", line 650, in modify\n    dn = self._modify(modify_childs, ignore_license=ignore_license, response=response, serverctrls=serverctrls)\n  File \"/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py\", line 1358, in _modify\n    ml = self._ldap_modlist()\n  File \"/usr/lib/python3/dist-packages/univention/admin/handlers/users/user.py\", line 1572, in _ldap_modlist\n    ml = self._check_password_history(ml, pwhistoryPolicy)\n  File \"/usr/lib/python3/dist-packages/univention/admin/handlers/users/user.py\", line 1646, in _check_password_history\n    raise univention.admin.uexceptions.pwalreadyused()\nunivention.admin.uexceptions.pwalreadyused: Das Passwort wurde bereits verwendet. Bitte wählen Sie ein anderes.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<stdin>\", line 107, in <module>\n  File \"<stdin>\", line 99, in _ansiballz_main\n  File \"<stdin>\", line 48, in invoke_module\n  File \"/usr/lib/python3.7/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.7/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib/python3.7/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_univention.ucs_modules.univention_directory_manager_payload_44udolus/ansible_univention.ucs_modules.univention_directory_manager_payload.zip/ansible_collections/univention/ucs_modules/plugins/modules/univention_directory_manager.py\", line 369, in <module>\n  File \"/tmp/ansible_univention.ucs_modules.univention_directory_manager_payload_44udolus/ansible_univention.ucs_modules.univention_directory_manager_payload.zip/ansible_collections/univention/ucs_modules/plugins/modules/univention_directory_manager.py\", line 355, in run_module\n  File \"/tmp/ansible_univention.ucs_modules.univention_directory_manager_payload_44udolus/ansible_univention.ucs_modules.univention_directory_manager_payload.zip/ansible_collections/univention/ucs_modules/plugins/modules/univention_directory_manager.py\", line 217, in _modify_object\n  File \"/usr/lib/python3/dist-packages/univention/udm/modules/generic.py\", line 207, in save\n    ), sys.exc_info()[2])\n  File \"/usr/lib/python3/dist-packages/six.py\", line 692, in reraise\n    raise value.with_traceback(tb)\n  File \"/usr/lib/python3/dist-packages/univention/udm/modules/generic.py\", line 201, in save\n    self.dn = self._orig_udm_object.modify()\n  File \"/usr/lib/python3/dist-packages/univention/admin/handlers/users/user.py\", line 1304, in modify\n    return super(object, self).modify(*args, **kwargs)\n  File \"/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py\", line 650, in modify\n    dn = self._modify(modify_childs, ignore_license=ignore_license, response=response, serverctrls=serverctrls)\n  File \"/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py\", line 1358, in _modify\n    ml = self._ldap_modlist()\n  File \"/usr/lib/python3/dist-packages/univention/admin/handlers/users/user.py\", line 1572, in _ldap_modlist\n    ml = self._check_password_history(ml, pwhistoryPolicy)\n  File \"/usr/lib/python3/dist-packages/univention/admin/handlers/users/user.py\", line 1646, in _check_password_history\n    raise univention.admin.uexceptions.pwalreadyused()\nunivention.udm.exceptions.ModifyError: Error saving 'users/user' object at 'uid=testuser1,ou=orgunit,dc=mydomain,dc=net': Das Passwort wurde bereits verwendet. Bitte wählen Sie ein anderes.\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

Is there a way to apply the password only on creation?
Something like the update_password option from the orphaned ansible module from @keachi
https://docs.ansible.com/ansible/latest/collections/community/general/udm_user_module.html#parameter-update_password

**Comment by michag86** [comment]
> https://github.com/ansible-collections/community.general/blob/main/plugins/modules/udm_user.py

This module is outdated:
https://github.com/ansible-collections/community.general/issues/2950#issuecomment-877827871

**Comment by vakilics** [comment]
I tested and looks promising. So, already fixed version can be found here: https://github.com/univention/ansible-modules/releases/tag/v3.1.4

**Comment by vakilics** [comment]
Hi, 
I tested it again with following and it works fine: 
cat user-chg_psswd-new.yml
```
---
- name: create a user
  hosts: pdn
  gather_facts: no
  tasks:
  - name: create a user
    univention_directory_manager:
      module: 'users/user'
      state: 'present'
      position: 'cn=Domain Users,cn=groups,dc=sh,dc=dev'
      set_properties:
        - property: 'username'
          value: 'testuser2'
        - property: 'lastname'
          value: 'testuser2'
        - property: 'password'
          value: 'super_secret_password'
```
and the output is below:
# ansible-playbook -i inventory user-chg_psswd-new.yml
```
/usr/lib/python3/dist-packages/paramiko/pkey.py:82: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from cryptography.hazmat.primitives.ciphers.algorithms in 48.0.0.
  "cipher": algorithms.TripleDES,
/usr/lib/python3/dist-packages/paramiko/transport.py:237: CryptographyDeprecationWarning: Blowfish has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.Blowfish and will be removed from cryptography.hazmat.primitives.ciphers.algorithms in 45.0.0.
  "class": algorithms.Blowfish,
/usr/lib/python3/dist-packages/paramiko/transport.py:261: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from cryptography.hazmat.primitives.ciphers.algorithms in 48.0.0.
  "class": algorithms.TripleDES,

PLAY [create a user] *************************************************************************************************************************************************************************

TASK [create a user] *************************************************************************************************************************************************************************
[WARNING]: Platform linux on host 10.200.34.120 is using the discovered Python interpreter at /usr/bin/python3.11, but future installation of another Python interpreter could change the
meaning of that path. See https://docs.ansible.com/ansible-core/2.17/reference_appendices/interpreter_discovery.html for more information.
changed: [10.200.34.120]

PLAY RECAP ***********************************************************************************************************************************************************************************
10.200.34.120              : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```
